##Kyle Braman, Donovan Dutcher, Nathaniel Plummer, William Bange

In [ ]:
# Import standard data and visualization libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# It seems there was an issue recently relating to tensorflow and Keras that broke the Top2Vec import: https://github.com/tensorflow/probability/issues/1795
# We attempt the workaround detailed here: https://github.com/tensorflow/tensorflow/releases/tag/v2.16.1
!pip install tf-keras~=2.16
import os
os.environ["TF_USE_LEGACY_KERAS"]="1"
import tf_keras as keras

# Import the Top2Vec
# This also requires installation on Colaboratory, as it's not pre-installed (😢)
!pip install top2vec[sentence_encoders]
from top2vec import Top2Vec

In [ ]:
GTC_V2 = pd.read_csv('https://raw.githubusercontent.com/MiriamSchirmer/genocide-transcript-corpus/main/Dataset_GTC-V2.csv', sep =';')
ECCC = GTC_V2.loc[GTC_V2['tribunal']=="ECCC"] #seperating into the ECCC tribunal

In [ ]:
documents = list(ECCC["text"]) #Convert the text column to a list
model = Top2Vec(documents, embedding_model='universal-sentence-encoder') #creating top2vec model

2024-04-11 15:04:31,704 - top2vec - INFO - Pre-processing documents for training
INFO:top2vec:Pre-processing documents for training
/usr/local/lib/python3.10/dist-packages/sklearn/feature_extraction/text.py:528: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
2024-04-11 15:04:35,025 - top2vec - INFO - Downloading universal-sentence-encoder model
INFO:top2vec:Downloading universal-sentence-encoder model
2024-04-11 15:04:45,788 - top2vec - INFO - Creating joint document/word embedding
INFO:top2vec:Creating joint document/word embedding
2024-04-11 15:04:55,931 - top2vec - INFO - Creating lower dimension embedding of documents
INFO:top2vec:Creating lower dimension embedding of documents
2024-04-11 15:05:16,510 - top2vec - INFO - Finding dense areas of documents
INFO:top2vec:Finding dense areas of documents
2024-04-11 15:05:17,343 - top2vec - INFO - Finding topics
INFO:top2vec:Finding topics


In [ ]:
model.get_num_topics() #Topic numbers

150

In [ ]:
topic_words, word_scores, topic_nums = model.get_topics(150)
topic_nums

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149])

In [ ]:
topic_words, word_scores, topic_scores, topic_nums = model.search_topics(keywords=["beat"], num_topics=5) #Looking at topics that pertain to death and killing
topic_nums

array([115, 128,  93,  75, 147])

In [ ]:
topic_words #The Topic words in these 5 topics

[array(['short', 'brief', 'long', 'court', 'break', 'briefly', 'longer',
        'small', 'little', 'early', 'courtroom', 'late', 'end', 'standing',
        'hold', 'down', 'arrest', 'up', 'time', 'waiting', 'keep', 'stop',
        'stand', 'hour', 'point', 'coup', 'off', 'rest', 'stopped',
        'clock', 'clear', 'talk', 'sit', 'mind', 'close', 'speak', 'focus',
        'fight', 'holding', 'detention', 'arrests', 'exit', 'big', 'beat',
        'conclusion', 'stay', 'younger', 'legs', 'speaking', 'old'],
       dtype='<U14'),
 array(['technical', 'video', 'issue', 'problem', 'incident', 'problems',
        'issues', 'record', 'story', 'subject', 'assist', 'talking',
        'cannot', 'matter', 'question', 'submission', 'rule', 'help',
        'trial', 'brief', 'talk', 'clarify', 'defence', 'inform', 'link',
        'interview', 'proceedings', 'related', 'word', 'instruction',
        'questions', 'experienced', 'expert', 'conflict', 'referring',
        'interviews', 'point', 'inform

In [ ]:
topic_words, word_scores, topic_nums = model.get_topics(146) #Investingating a single instance
topic_words[120]

array(['president', 'chairman', 'mr', 'chief', 'leader', 'judge', 'exact',
       'correct', 'sir', 'husband', 'married', 'mrs', 'democratic',
       'political', 'one', 'person', 'responsible', 'hear', 'proper',
       'letter', 'madam', 'respect', 'comrade', 'personal', 'official',
       'an', 'right', 'ern', 'interpretation', 'yes', 'indeed', 'clearly',
       'recognize', 'stated', 'counsel', 'behalf', 'father', 'correctly',
       'someone', 'chanphal', 'himself', 'referring', 'personnel',
       'somebody', 'speaking', 'real', 'officials', 'ms', 'testified',
       'asked'], dtype='<U14')

#Top2Vec with only accused being Kaing

In [ ]:
GTC_V2 = pd.read_csv('https://raw.githubusercontent.com/MiriamSchirmer/genocide-transcript-corpus/main/Dataset_GTC-V2.csv', sep =';')
ECCC = GTC_V2.loc[GTC_V2['tribunal']=="ECCC"] #seperating into the ECCC tribunal
Kaing=ECCC.loc[ECCC['accused']=='Kaing Guev Eav']

In [ ]:
Kaing

tribunal id_transcript     case         accused  \
16862     ECCC       E1/12.1  Case001  Kaing Guev Eav   
16863     ECCC       E1/12.1  Case001  Kaing Guev Eav   
16864     ECCC       E1/12.1  Case001  Kaing Guev Eav   
16865     ECCC       E1/12.1  Case001  Kaing Guev Eav   
16866     ECCC       E1/12.1  Case001  Kaing Guev Eav   
...        ...           ...      ...             ...   
32733     ECCC       E1/42.1  Case001  Kaing Guev Eav   
32734     ECCC       E1/42.1  Case001  Kaing Guev Eav   
32735     ECCC       E1/42.1  Case001  Kaing Guev Eav   
32736     ECCC       E1/42.1  Case001  Kaing Guev Eav   
32737     ECCC       E1/42.1  Case001  Kaing Guev Eav   

                          date  \
16862  2009-04-20 00:00:00 UTC   
16863  2009-04-20 00:00:00 UTC   
16864  2009-04-20 00:00:00 UTC   
16865  2009-04-20 00:00:00 UTC   
16866  2009-04-20 00:00:00 UTC   
...                        ...   
32733  2009-07-02 00:00:00 UTC   
32734  2009-07-02 00:00:00 UTC   
32735  2009-07-02 00:00:00 UTC   
32736  2009-07-02 00:00:00 UTC   
32737  2009-07-02 00:00:00 UTC   

                                                    text  trauma  \
16862  P R O C E E D I N G S (Judges enter the courtr...       0   
16863  MR. PRESIDENT: This morning the Trial Chamber ...       0   
16864  THE GREFFIER: Your Honours, Mr. President, the...       0   
16865  MR. PRESIDENT: Greffier put those records of t...       0   
16866                         (Witness enters courtroom)       0   
...                                                  ...     ...   
32733  MS. CANIZARES: I have no further questions for...       0   
32734  MR. PRESIDENT: Mr. Kaing Guek Eav, do you have...       0   
32735  THE ACCUSED: Mr. President, in the matter of c...       0   
32736  MR. PRESIDENT: The hearing of the testimony of...       0   
32737  (Judges exit courtroom) (Court adjourns at 1603H)       0   

                    role                                witnesses  \
16862  Court Proceedings  [Chan Voeun (KW-31), Chan Khan (KW-32)]   
16863          JudgeProc  [Chan Voeun (KW-31), Chan Khan (KW-32)]   
16864  Court Proceedings  [Chan Voeun (KW-31), Chan Khan (KW-32)]   
16865          JudgeProc  [Chan Voeun (KW-31), Chan Khan (KW-32)]   
16866  Court Proceedings  [Chan Voeun (KW-31), Chan Khan (KW-32)]   
...                  ...                                      ...   
32733         LawyerProc                         [Norng Chanphal]   
32734            JudgeQA                         [Norng Chanphal]   
32735            Accused                         [Norng Chanphal]   
32736          JudgeProc                         [Norng Chanphal]   
32737  Court Proceedings                         [Norng Chanphal]   

       n_witnesses   start             id_annotation  \
16862            2       0  63b1f39c97ad59b4cfc5793d   
16863            2      51  63b1f3a397ad59b4cfc5793e   
16864            2     267  63b1f3a797ad59b4cfc5793f   
16865            2     418  63b1f3a997ad59b4cfc57940   
16866            2     571  63b1f3ab97ad59b4cfc57941   
...            ...     ...                       ...   
32733            1  119732  63bddfe797ad59b4cfc5ba94   
32734            1  120532  63bddff597ad59b4cfc5ba95   
32735            1  120848  63bddff997ad59b4cfc5ba96   
32736            1  121386  63bde00897ad59b4cfc5ba97   
32737            1  122325  63bde00b97ad59b4cfc5ba98   

                    id_document  \
16862  63a60e2397ad59b4cfc571ec   
16863  63a60e2397ad59b4cfc571ec   
16864  63a60e2397ad59b4cfc571ec   
16865  63a60e2397ad59b4cfc571ec   
16866  63a60e2397ad59b4cfc571ec   
...                         ...   
32733  63a60e2797ad59b4cfc5721a   
32734  63a60e2797ad59b4cfc5721a   
32735  63a60e2797ad59b4cfc5721a   
32736  63a60e2797ad59b4cfc5721a   
32737  63a60e2797ad59b4cfc5721a   

                                                     url  
16862  http://www.eccc.gov.kh/sites/default/files/doc...  
16863  http://www.eccc.gov.kh/sites/default/files/doc.

In [ ]:
documents = list(Kaing["text"]) #Convert the text column to a list
model = Top2Vec(documents, embedding_model='universal-sentence-encoder')

2024-04-11 14:23:23,681 - top2vec - INFO - Pre-processing documents for training
INFO:top2vec:Pre-processing documents for training
/usr/local/lib/python3.10/dist-packages/sklearn/feature_extraction/text.py:528: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
2024-04-11 14:23:24,759 - top2vec - INFO - Downloading universal-sentence-encoder model
INFO:top2vec:Downloading universal-sentence-encoder model
2024-04-11 14:23:31,039 - top2vec - INFO - Creating joint document/word embedding
INFO:top2vec:Creating joint document/word embedding
2024-04-11 14:23:35,867 - top2vec - INFO - Creating lower dimension embedding of documents
INFO:top2vec:Creating lower dimension embedding of documents
2024-04-11 14:23:53,738 - top2vec - INFO - Finding dense areas of documents
INFO:top2vec:Finding dense areas of documents
2024-04-11 14:23:54,077 - top2vec - INFO - Finding topics
INFO:top2vec:Finding topics


In [ ]:
model.get_num_topics()

87

In [ ]:
topic_words, word_scores, topic_nums = model.get_topics(87)
topic_nums

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86])

In [ ]:
topic_words, word_scores, topic_scores, topic_nums = model.search_topics(keywords=["interrogation"], num_topics=5) #Looking at topics that pertain to death and killing
topic_nums

array([ 8, 24, 75,  7,  0])

In [ ]:
topic_words

[array(['detainees', 'prisoners', 'prisoner', 'detainee', 'detained',
        'interrogated', 'interrogation', 'detention', 'torture', 'prison',
        'tortures', 'tortured', 'interrogate', 'interrogations',
        'interrogator', 'guards', 'executed', 'arrest', 'guarded',
        'arrested', 'interrogators', 'cell', 'guarding', 'sessions',
        'accused', 'cells', 'courtroom', 'khmer', 'gruel', 'escape',
        'soldiers', 'treated', 'provided', 'chamber', 'testimony',
        'hospital', 'judges', 'committed', 'prosecutor', 'meeting',
        'shackles', 'cia', 'prosecutors', 'members', 'trial', 'officer',
        'session', 'questioning', 'asked', 'cambodia'], dtype='<U14'),
 array(['interrogated', 'interrogation', 'detainees', 'interrogations',
        'interrogate', 'interrogator', 'detainee', 'detained', 'prisoners',
        'confession', 'torture', 'questioning', 'prisoner', 'tortured',
        'accused', 'tortures', 'detention', 'prosecutor', 'testimony',
        'procee

# ICTY

In [ ]:
GTC_V2 = pd.read_csv('https://raw.githubusercontent.com/MiriamSchirmer/genocide-transcript-corpus/main/Dataset_GTC-V2.csv', sep =';')
ICTY = GTC_V2.loc[GTC_V2['tribunal']=="ICTY"] #Seperating into the ICTY model

In [ ]:
documents_ICTY = list(ICTY["text"])
model_ICTY = Top2Vec(documents_ICTY, embedding_model='universal-sentence-encoder') #Generating Top2Vec using the universal sentence encoders

2024-03-16 03:33:02,929 - top2vec - INFO - Pre-processing documents for training
INFO:top2vec:Pre-processing documents for training
/usr/local/lib/python3.10/dist-packages/sklearn/feature_extraction/text.py:528: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
2024-03-16 03:33:05,790 - top2vec - INFO - Downloading universal-sentence-encoder model
INFO:top2vec:Downloading universal-sentence-encoder model
2024-03-16 03:33:15,448 - top2vec - INFO - Creating joint document/word embedding
INFO:top2vec:Creating joint document/word embedding
2024-03-16 03:33:26,438 - top2vec - INFO - Creating lower dimension embedding of documents
INFO:top2vec:Creating lower dimension embedding of documents
2024-03-16 03:33:55,742 - top2vec - INFO - Finding dense areas of documents
INFO:top2vec:Finding dense areas of documents
2024-03-16 03:33:57,393 - top2vec - INFO - Finding topics
INFO:top2vec:Finding topics


In [ ]:
model_ICTY.get_num_topics()

168

In [ ]:
topic_words, word_scores, topic_nums = model_ICTY.get_topics(161)
topic_nums

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160])

In [ ]:
topic_sizes, topic_nums = model_ICTY.get_topic_sizes()
topic_sizes

array([800, 641, 593, 535, 473, 468, 460, 458, 426, 369, 356, 322, 302,
       295, 276, 261, 261, 233, 230, 228, 219, 216, 205, 193, 190, 184,
       177, 176, 172, 172, 167, 160, 158, 154, 152, 147, 141, 140, 139,
       134, 129, 129, 126, 124, 123, 123, 121, 120, 119, 117, 113, 113,
       106, 104, 100,  99,  97,  95,  94,  93,  91,  90,  89,  89,  87,
        87,  87,  87,  84,  83,  83,  82,  82,  79,  78,  78,  77,  76,
        75,  73,  73,  72,  72,  71,  69,  69,  68,  68,  68,  68,  66,
        66,  66,  65,  64,  63,  62,  58,  58,  58,  56,  55,  55,  53,
        53,  53,  53,  51,  50,  50,  50,  49,  48,  48,  47,  46,  46,
        46,  46,  45,  45,  44,  44,  42,  42,  42,  41,  39,  39,  39,
        39,  38,  38,  37,  37,  37,  37,  37,  36,  36,  35,  35,  34,
        34,  34,  34,  33,  33,  32,  32,  31,  31,  31,  30,  30,  29,
        29,  28,  28,  27,  26,  26,  26,  25,  23,  22,  21,  20])

In [ ]:
topic_words, word_scores, topic_scores, topic_nums = model_ICTY.search_topics(keywords=["kill"], num_topics=5) #Search for topics containing the keyword, "kill"
topic_nums

array([124, 160,  46, 127, 109])

In [ ]:
topic_words #https://www.pbs.org/wgbh/pages/frontline/shows/karadzic/atrocities/omarska.html trnopolje
#https://www.fulcrum.org/concern/file_sets/bk128d143 karaterm

[array(['defence', 'video', 'counsel', 'testified', 'testifying', 'trial',
        'record', 'accused', 'transcript', 'courtroom', 'read', 'testify',
        'referring', 'admitted', 'talked', 'prosecution', 'recognise',
        'shooting', 'recall', 'assist', 'mentioned', 'incident',
        'keraterm', 'begic', 'guards', 'recognised', 'called', 'beaten',
        'referred', 'redacted', 'court', 'testimony', 'heard', 'armed',
        'attack', 'stood', 'takeover', 'talk', 'interview', 'hear',
        'witness', 'transcripts', 'review', 'objection', 'issue',
        'familiar', 'brought', 'clarify', 'registrar', 'identify'],
       dtype='<U14'),
 array(['witness', 'testifying', 'witnesses', 'stood', 'testified',
        'testimony', 'testify', 'stopped', 'turned', 'remained', 'entered',
        'brought', 'popovic', 'returned', 'detained', 'leave', 'became',
        'prosecution', 'accused', 'prosecutor', 'proceed', 'surrender',
        'fell', 'told', 'reached', 'trial', 'remain', 'd

# ICTR

In [ ]:
GTC_V2 = pd.read_csv('https://raw.githubusercontent.com/MiriamSchirmer/genocide-transcript-corpus/main/Dataset_GTC-V2.csv', sep =';')
ICTR = GTC_V2.loc[GTC_V2['tribunal']=="ICTR"] #Separate into the ICTR tribunal

In [ ]:
documents_ICTR = list(ICTR["text"])
model_ICTR = Top2Vec(documents_ICTR, embedding_model='universal-sentence-encoder') #Generate a Top2Vec model using the universal sentence encoders

2024-03-16 03:37:28,738 - top2vec - INFO - Pre-processing documents for training
INFO:top2vec:Pre-processing documents for training
/usr/local/lib/python3.10/dist-packages/sklearn/feature_extraction/text.py:528: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
2024-03-16 03:37:30,494 - top2vec - INFO - Downloading universal-sentence-encoder model
INFO:top2vec:Downloading universal-sentence-encoder model
2024-03-16 03:37:39,254 - top2vec - INFO - Creating joint document/word embedding
INFO:top2vec:Creating joint document/word embedding
2024-03-16 03:37:47,823 - top2vec - INFO - Creating lower dimension embedding of documents
INFO:top2vec:Creating lower dimension embedding of documents
2024-03-16 03:38:09,037 - top2vec - INFO - Finding dense areas of documents
INFO:top2vec:Finding dense areas of documents
2024-03-16 03:38:10,933 - top2vec - INFO - Finding topics
INFO:top2vec:Finding topics


In [ ]:
model_ICTR.get_num_topics()

158

In [ ]:
topic_words, word_scores, topic_nums = model_ICTR.get_topics(160)
topic_nums

ValueError: num_topics cannot exceed the number of topics: 139.

In [ ]:
topic_sizes, topic_nums = model_ICTR.get_topic_sizes()
topic_sizes

In [ ]:
topic_words, word_scores, topic_scores, topic_nums = model_ICTR.search_topics(keywords=["beat"], num_topics=5) #Search for topics containing the keyword, "Beat"
topic_nums

In [ ]:
topic_words, word_scores, topic_nums = model_ICTR.get_topics(160)
topic_words[107]