In [1]:
# Import standard data and visualization libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# Import the Top2Vec
# This also requires installation on Colaboratory, as it's not pre-installed (😢)
!pip install top2vec[sentence_encoders]
from top2vec import Top2Vec

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.7/85.7 kB 3.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.2/5.2 MB 12.8 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.2/5.2 MB 36.5 MB/s eta 0:00:00
  Using cached Cython-0.29.37-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (1.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.8/56.8 kB 6.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 589.8/589.8 MB 1.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.3/5.3 MB 82.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 64.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 93.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 63.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/MiriamSchirmer/genocide-transcript-corpus/main/Dataset_GTC-V2.csv', sep =';')

df = df[df["role"] == "Witness"] #Change so only witnesses speak

df = df.loc[df['tribunal']=="ECCC"]
df

tribunal id_transcript     case         accused  \
16868     ECCC       E1/12.1  Case001  Kaing Guev Eav   
16870     ECCC       E1/12.1  Case001  Kaing Guev Eav   
16872     ECCC       E1/12.1  Case001  Kaing Guev Eav   
16874     ECCC       E1/12.1  Case001  Kaing Guev Eav   
16876     ECCC       E1/12.1  Case001  Kaing Guev Eav   
...        ...           ...      ...             ...   
32724     ECCC       E1/42.1  Case001  Kaing Guev Eav   
32726     ECCC       E1/42.1  Case001  Kaing Guev Eav   
32728     ECCC       E1/42.1  Case001  Kaing Guev Eav   
32730     ECCC       E1/42.1  Case001  Kaing Guev Eav   
32732     ECCC       E1/42.1  Case001  Kaing Guev Eav   

                          date  \
16868  2009-04-20 00:00:00 UTC   
16870  2009-04-20 00:00:00 UTC   
16872  2009-04-20 00:00:00 UTC   
16874  2009-04-20 00:00:00 UTC   
16876  2009-04-20 00:00:00 UTC   
...                        ...   
32724  2009-07-02 00:00:00 UTC   
32726  2009-07-02 00:00:00 UTC   
32728  2009-07-02 00:00:00 UTC   
32730  2009-07-02 00:00:00 UTC   
32732  2009-07-02 00:00:00 UTC   

                                                    text  trauma     role  \
16868        MR. CHAN VOEUN: Yes, my name is Chan Voeun.       0  Witness   
16870                 MR. CHAN VOEUN: I am 56 years old.       0  Witness   
16872     MR. CHAN VOEUN: I live in Amleang subdistrict.       0  Witness   
16874                      MR. CHAN VOEUN: I'm a farmer.       0  Witness   
16876                   MR. CHAN VOEUN: That is correct.       0  Witness   
...                                                  ...     ...      ...   
32724  A. He said the people who lived here had suffe...       0  Witness   
32726  A. I remember that when I returned to Tuol Sle...       0  Witness   
32728  A. The DC-Cam learned that I was the child sur...       0  Witness   
32730  A. I cannot remember it but I probably do not ...       0  Witness   
32732  A. I think I met with them for a short period ...       0  Witness   

                                     witnesses  n_witnesses   start  \
16868  [Chan Voeun (KW-31), Chan Khan (KW-32)]            2     638   
16870  [Chan Voeun (KW-31), Chan Khan (KW-32)]            2     724   
16872  [Chan Voeun (KW-31), Chan Khan (KW-32)]            2     805   
16874  [Chan Voeun (KW-31), Chan Khan (KW-32)]            2     892   
16876  [Chan Voeun (KW-31), Chan Khan (KW-32)]            2    1070   
...                                        ...          ...     ...   
32724                         [Norng Chanphal]            1  117126   
32726                         [Norng Chanphal]            1  117525   
32728                         [Norng Chanphal]            1  118031   
32730                         [Norng Chanphal]            1  118707   
32732                         [Norng Chanphal]            1  119203   

                  id_annotation               id_document  \
16868  63b1f69297ad59b4cfc579ce  63a60e2397ad59b4cfc571ec   
16870  63b1f69597ad59b4cfc579cf  63a60e2397ad59b4cfc571ec   
16872  63b1f69897ad59b4cfc579d0  63a60e2397ad59b4cfc571ec   
16874  63b1f69a97ad59b4cfc579d1  63a60e2397ad59b4cfc571ec   
16876  63b1f69d97ad59b4cfc579d2  63a60e2397ad59b4cfc571ec   
...                         ...                       ...   
32724  63bde01797ad59b4cfc5ba9a  63a60e2797ad59b4cfc5721a   
32726  63bde01a97ad59b4cfc5ba9b  63a60e2797ad59b4cfc5721a   
32728  63bde01d97ad59b4cfc5ba9c  63a60e2797ad59b4cfc5721a   
32730  63bde02097ad59b4cfc5ba9d  63a60e2797ad59b4cfc5721a   
32732  63bde02497ad59b4cfc5ba9e  63a60e2797ad59b4cfc5721a   

                                                     url  
16868  http://www.eccc.gov.kh/sites/default/files/doc...  
16870  http://www.eccc.gov.kh/sites/default/files/doc...  
16872  http://www.eccc.gov.kh/sites/default/files/doc...  
16874  http://www.eccc.gov.kh/sites/default/files/doc...  
16876  http://www.eccc.gov.kh/sites/default/files/doc...  
...                                            

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# Import the LDA items from scikit-learn
from sklearn.decomposition import LatentDirichletAllocation
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import *

In [ ]:
def drop(text): #Getting rid of names at beginning
    if ": " in text:
        return text[text.index(":")+2:]
    else:
        return text

def q(text): #Getting rid of the text being prefaced with Q.
  if "Q." in text:
    return text[text.index("Q.")+3:]
  else:
    return text

def a(text): #Getting rid of the text being prefaced with A.
  if "A." in text:
    return text[text.index("A.")+3:]
  else:
    return text

def interpretation(text): #Getting rid of the bracketed interpretation section
  if "[Interpretation]" in text:
    return text[text.index("[Interpretation]")+16:]
  else:
    return text

def strip(text): #Getting rid of white space
  return text.strip()


df["text"] = df["text"].apply(interpretation)
df["text"] = df["text"].apply(a)
df["text"] = df["text"].apply(q)

df["text"] = df["text"].apply(drop)
df["text"] = df["text"].apply(strip)

In [ ]:
documents = list(df["text"])
model = Top2Vec(documents, embedding_model='universal-sentence-encoder')

2024-04-12 22:13:05,183 - top2vec - INFO - Pre-processing documents for training
INFO:top2vec:Pre-processing documents for training
2024-04-12 22:13:05,963 - top2vec - INFO - Downloading universal-sentence-encoder model
INFO:top2vec:Downloading universal-sentence-encoder model
2024-04-12 22:13:13,713 - top2vec - INFO - Creating joint document/word embedding
INFO:top2vec:Creating joint document/word embedding
2024-04-12 22:13:17,006 - top2vec - INFO - Creating lower dimension embedding of documents
INFO:top2vec:Creating lower dimension embedding of documents
2024-04-12 22:13:31,572 - top2vec - INFO - Finding dense areas of documents
INFO:top2vec:Finding dense areas of documents
2024-04-12 22:13:31,823 - top2vec - INFO - Finding topics
INFO:top2vec:Finding topics


In [ ]:
model.get_num_topics()

63

In [ ]:
topic_sizes, topic_nums = model.get_topic_sizes()
topic_sizes

array([458, 318, 293, 207, 187, 187, 185, 165, 153, 150, 144, 137, 136,
       136, 132, 132, 128, 124, 122, 119, 116, 103,  97,  92,  91,  89,
        85,  80,  80,  77,  75,  72,  71,  70,  70,  67,  61,  60,  60,
        58,  57,  56,  55,  53,  53,  49,  44,  43,  42,  41,  40,  40,
        39,  39,  38,  37,  35,  35,  34,  33,  32,  20,  18])

In [ ]:
topic_words, word_scores, topic_nums = model.get_topics(20)
topic_num = 0
pd.DataFrame(topic_words[topic_num],word_scores[topic_num])
#topic_words[0]

0
0.637814      detainees
0.565812      prisoners
0.537830       prisoner
0.528980       detainee
0.500911       detained
0.435843   interrogated
0.412154         guards
0.402095         prison
0.355853  interrogation
0.338032        torture
0.330647       tortured
0.276968         arrest
0.273730          guard
0.269038           held
0.240416       soldiers
0.235934       sessions
0.234983       arrested
0.231417        accused
0.213403          khmer
0.207421           kept
0.204239        members
0.199001       hospital
0.197392       security
0.192702        treated
0.191392          fence
0.190752        workers
0.189730       cambodia
0.187214      committed
0.186569          gruel
0.185476        chamber
0.184703           were
0.176721          staff
0.176114    cooperative
0.173041            cia
0.168264        session
0.165080       meetings
0.165044         killed
0.162050       assigned
0.161459         member
0.160771        meeting
0.160325         pagoda
0.155669          phnom
0.155190         stayed
0.147810            had
0.147513          court
0.145482    disappeared
0.145069            sar
0.144141            saw
0.143723     instructed
0.143539          floor

In [ ]:
topic_words, word_scores, topic_scores, topic_nums = model.search_topics(keywords=["beat", "blood"], num_topics=20)
topic_nums

array([56, 25, 30, 62, 31, 36, 52, 41, 40, 32, 46, 20, 49, 34, 12, 26,  9,
       60, 61, 55])

In [ ]:
topic_words #9, 30

[array(['no', 'not', 'yes', 'only', 'actually', 'chea', 'already', 'sure',
        'never', 'nothing', 'didn', 'really', 'cannot', 'afraid', 'quite',
        'any', 'still', 'are', 'nol', 'rather', 'correct', 'would', 'is',
        'off', 'of', 'that', 'removed', 'very', 'it', 'just', 'has',
        'probably', 'given', 'was', 'way', 'there', 'too', 'out', 'have',
        'always', 'kind', 'issue', 'tried', 'maybe', 'mentioned', 'one',
        'do', 'so', 'well', 'were'], dtype='<U13'),
 array(['yes', 'sure', 'no', 'correct', 'actually', 'well', 'not',
        'really', 'right', 'quite', 'only', 'very', 'kind', 'just',
        'probably', 'first', 'one', 'it', 'already', 'chea', 'maybe', 'so',
        'that', 'there', 'way', 'clearly', 'have', 'is', 'always', 'has',
        'any', 'simply', 'much', 'some', 'while', 'think', 'believe',
        'far', 'course', 'question', 'bit', 'most', 'would', 'too', 'him',
        'although', 'tell', 'are', 'was', 'on'], dtype='<U13'),
 array(['tortu

In [ ]:
documents, document_scores, document_ids = model.search_documents_by_topic(topic_num=46, num_docs=10)

In [ ]:
documents

array(['I am a farmer, a rice farmer.', 'I am a farmer.',
       'I am a farmer.', 'I am a farmer.', 'I am a farmer.',
       "I'm a farmer.", 'I am a rice farmer.', 'I am a rice farmer.',
       'I am a rice farmer.', 'I was a rice farmer.',
       'I am doing farming.', 'I am a peasant.  I do farming.',
       'I live at Chey Mungkul Balaing, Kampong Thom, and I am a rice farmer.',
       'I sometimes did farming and sometimes I planted vegetables.',
       'I worked in the farm and in the plantation, and I also raised livestock.',
       'I used to guard them while they were planting potatoes.',
       'I am a farmer and I collect palm juice.',
       'I am at home planting vegetables.',
       'At that time, I stopped being a soldier and I became a farmer.',
       'After I was defrocked, I was transferred to work in a cooperative, to work on farming and rice transplanting.'],
      dtype=object)

In [ ]:
topic_nums, topic_scores, topic_words, word_scores = model.get_documents_topics([1], num_topics=5)
word_scores

array([[[0.48934066, 0.47565466, 0.43942004, 0.37114778, 0.37054715,
         0.3556832 , 0.3362631 , 0.32830763, 0.32316825, 0.2882176 ,
         0.286552  , 0.28011853, 0.27429456, 0.26329145, 0.2522779 ,
         0.2519794 , 0.25004202, 0.24452619, 0.24142657, 0.23810978,
         0.23437059, 0.23055604, 0.226749  , 0.22615784, 0.22197053,
         0.2186825 , 0.21565416, 0.21249913, 0.20953502, 0.20740664,
         0.20584619, 0.20537469, 0.20357421, 0.19722143, 0.1958029 ,
         0.19428001, 0.19088304, 0.18844354, 0.18792182, 0.1818048 ,
         0.18025488, 0.17728513, 0.17581105, 0.17563945, 0.17334008,
         0.17246449, 0.17221475, 0.17211956, 0.1708767 , 0.17006814],
        [0.5401831 , 0.5099597 , 0.48605448, 0.4417501 , 0.41904998,
         0.4061516 , 0.40418905, 0.4007985 , 0.391848  , 0.3889531 ,
         0.3827814 , 0.37703332, 0.37236527, 0.37183297, 0.3703251 ,
         0.36442715, 0.36127502, 0.36089957, 0.35792083, 0.3560418 ,
         0.35464352, 0.35290855, 

In [ ]:
topic_nums, topic_scores, topic_words, word_scores = model.get_documents_topics([51], num_topics=5)#51,145,20,98,67,118,80,126,44
topic_nums

array([[12, 24, 13, 83, 11]])